### ISSUE TITLE
custom dns servers field documentation and UI display

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#104]
When adding a library network that has multiple custom DNS servers, the field help should state that the comma separated list of DNS servers should not include spaces. A space after a comma causes the save step to fail. Additionally, the display of DNS servers is inside curly braces in the UI which should be removed when displaying the saved value:
![image](https://user-images.githubusercontent.com/4633345/95771676-794bdd80-0c89-11eb-9128-85acb93b2716.png)

**Comment by rudietuesdays** [comment]
Looks like some of this code that had been done to address this was lost in a merge, adding back in now!

**Comment by jheretic** [comment]
Fixed by #106
