### ISSUE TITLE
Top Widgets: the main focus is the number (median speed) rather than the chart

### ISSUE THREAD

**Issue by smithkelseyj** [throneless-tech/murakami-viz#16]

**Comment by rudietuesdays** [comment]
@smithkelseyj is this still an issue? The top widgets reflect the wireframes directly now (I think the updates may not have been merged when this issue was opened) so I'd like to close it unless there's changes to be made!

**Comment by smithkelseyj** [comment]
I can check but I don't remember how to log in to MLBN. Could you send me those details?

**Comment by rudietuesdays** [comment]
Yup! (http://viz.measuringbroadband.org:3000/)[http://viz.measuringbroadband.org:3000/admin]

I'll message you the user and pw on slack

**Comment by smithkelseyj** [comment]
As far as I can remember, looks good!

**Comment by rudietuesdays** [comment]
Thanks! Closing then
