### ISSUE TITLE
When not logged in, page should redirect to the login interface (and login page should be the default page for anonymous users)

### ISSUE THREAD

**Issue by jheretic** [throneless-tech/murakami-viz#2]
Currently the site does not redirect users to the login screen when they attempt to load the site. Anonymous users should automatically be redirected to `/login` and `/login` should be the default page for non-logged-in users.

**Comment by rudietuesdays** [comment]
@jheretic can you review when you get a sec? Thank you!

**Comment by jheretic** [comment]
This looks like it's working, but waiting for https://github.com/throneless-tech/murakami-viz/pull/11 to get merged for some final testing before closing out.

**Comment by jheretic** [comment]
This works, but also redirects you on login when you refresh the page even if logged in, so still a bit of a problem.
