### ISSUE TITLE
Change "View" to "Group by" on chart

### ISSUE THREAD

**Issue by smithkelseyj** [throneless-tech/murakami-viz#24]
Users are not realizing that the “By Hour”, “By Day”, “By Month” are different ways to group the data. "By Hour, By Day, By Month" is understood as zoom-in buttons, not as aggregations/different views.
Suggestion: Change the language to be “Group By ____”

But also, could this to moved to sidebar date picker?

**Comment by rudietuesdays** [comment]
@smithkelseyj pushed the update for the "Group by langauge" but I'm not sure I follow for where it should get moved. Should the entire line be moved under/next to the date ranger picker?

**Comment by smithkelseyj** [comment]
I don't know if that's been decided yet. We can discuss tomorrow. Sorry for the confusion!
