### ISSUE TITLE
Add hover tooltips with definitions of terms

### ISSUE THREAD

**Issue by smithkelseyj** [throneless-tech/murakami-viz#27]
https://docs.google.com/document/d/10h9WWXAmgFIRbap9lgw8CW7o5BHpMv0F-nNCDSa8tXw/edit

**Comment by rudietuesdays** [comment]
Tooltips are back in per [this commit](https://github.com/throneless-tech/murakami-viz/commit/6ebd913f682687657486142f974d056c308ebd7d) (apologies, forgot to link in the commit)
