### ISSUE TITLE
Add ability to show data from multiple connections (wifi, wired) on a single graph

### ISSUE THREAD

**Issue by smithkelseyj** [throneless-tech/murakami-viz#28]
Users are interested in the comparison of wifi and wired.

- neither is selected = Both (aggregate, 1 line on the chart)
- Wifi is selected = Wifi only
- Wired is selected = Wired only
- wifi and wired selected = Both (2 lines on the chart)

**Comment by rudietuesdays** [comment]
Closing; this was merged in via a graph fixes branch (apologies for not referencing the issue)
