### ISSUE TITLE
Add date picker to "add a note"

### ISSUE THREAD

**Issue by smithkelseyj** [throneless-tech/murakami-viz#29]

**Comment by rudietuesdays** [comment]
@smithkelseyj confirming this should be added to Edit Note, not add note?

**Comment by smithkelseyj** [comment]
I noticed that there wasn't a pop-up calendar for add a note and edit note.

**Comment by jheretic** [comment]
Apparently the datepicker is there but not showing up in Firefox. We're investigating further.
