### ISSUE TITLE
Character or word limits on text fields are undocumented

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#54]
There appears to be a character or word limit on the about field, but not sure what that limit is. I've attempted to paste the About content we drafted into this field, which is too long, but shorter strings appear to save properly. The error message is not very helpful:
![image](https://user-images.githubusercontent.com/4633345/84157890-3eb30980-aa39-11ea-9f12-a2278b14b201.png)

* Please document the character/word limits and how to change them
* Please make the error message more informative

**Comment by critzo** [comment]
Same thing on other fields like Contact and Forum.

**Comment by critzo** [comment]
For reference, this is the content I wish to add for the About and Contact content:
https://docs.google.com/document/d/1u5FZiOEA0k67wRpRJygDbt1JhJZN3_StCqwXiMYJo-E/edit#

**Comment by rudietuesdays** [comment]
@critzo I'm able to add this content locally and wondering if the issue was fixed via another issue close out -- could you try it on a newer demo and let me know if the issue persists?
