### ISSUE TITLE
Edit to glossary term not working, odd error after success message

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#55]
I added a glossary term, with a link at the end. Saved successfully.
I then edited the term, attempting to add the <a href.. tag to it. 
When saving, I get a success message, then an error message, and the change is not saved. See screenshots.

![image](https://user-images.githubusercontent.com/4633345/84158966-825a4300-aa3a-11ea-82cb-4ef10bbb9206.png)
![image](https://user-images.githubusercontent.com/4633345/84159039-9736d680-aa3a-11ea-8892-3f1884379a5a.png)
![image](https://user-images.githubusercontent.com/4633345/84159075-a158d500-aa3a-11ea-8f05-aa6e2bc394af.png)

**Comment by rudietuesdays** [comment]
@jheretic can you review PR #80 and let me know if we can close this out? Thanks!
