### ISSUE TITLE
HTML links not rendering in Glossary

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#56]
Separate from #55, HTML is not rendered in the glossary, but presented as text:
![image](https://user-images.githubusercontent.com/4633345/84159341-f85eaa00-aa3a-11ea-8d5e-8fd63d2dbe3a.png)

**Comment by rudietuesdays** [comment]
Should be fixed by #80 (related to #55)

**Comment by rudietuesdays** [comment]
@jheretic bumping #80 review for this issue too!

**Comment by rudietuesdays** [comment]
Tested and working in the live environment; closing.
