### ISSUE TITLE
No way to remove users, locations

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#57]
Perhaps we didn't include "remove" as a function in the mockups, but users in the admin role (for all locations) and in the editor role (for assigned locations) should be able to remove users and locations. There seems to be no way to do this currently.

**Comment by rudietuesdays** [comment]
Opened pull #84 to fix this issue, asking for review from @jheretic

**Comment by rudietuesdays** [comment]
#84 merged, closing.
