### ISSUE TITLE
Viewer test user does not see library assigned to them

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#61]
Logged in as my viewer test user (username: critzo), the account doesn't appear to be assigned to a library, though when logged in as the admin account, the MLK library seems to have three users assigned to it. 
![image](https://user-images.githubusercontent.com/4633345/84164669-ccdebe00-aa40-11ea-9546-ed9c828786ea.png)

**Comment by rudietuesdays** [comment]
@jheretic @critzo working locally; bumping this for testing in the sandbox.

**Comment by rudietuesdays** [comment]
Tested on a new demo and is working as expected! Closing for now.
