### ISSUE TITLE
Dashboard page loads really slow for viewer role user 

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#62]
When initially logging in as user `critzo`, a blank page is displayed for ~3-5 seconds before the Dashboard page loads. This also happens whenever this user clicks back to the Dashboard page. There is a very brief, small "loading" message at the top left of the page, but no other indicators that something is happening.

**Comment by rudietuesdays** [comment]
Tested on a new demo instance and this issue does not appear to persist. Closing for now.
