### ISSUE TITLE
Viewer role not displayed near username

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#63]
When I initially logged in as user `critzo` I thought it was an editor account, but it's a viewer account. At the top right near my name/account info, I was expecting my user role to be displayed, but it's not.

**Comment by rudietuesdays** [comment]
@critzo I believe this has been fixed via other fixes because it appears locally now! Bumping for sandbox testing with the latest version; will look into it if it doesn't show still.

**Comment by rudietuesdays** [comment]
Fixed on the latest demo instance; closing.
