### ISSUE TITLE
Add new device form does not submit

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#71]
I attempted to add a new device to a library but the form does not submit. Here are the values I was using if it's helpful:

Device Name: bennington-egress-wired
Device ID: 0ce3deb83d74a4f01fa44909b11cde455afc9c69937369a3dcdfd3bbdb5dd7
Network Type: public (though if "egress" was an option I would select it)
Connection Type: wired
MAC Address: 00:1e:06:37:07:4e

**Comment by rudietuesdays** [comment]
@critzo tested on latest demo instance and I'm able to add a device successfully, so closing for now! Let me know if this issue persists.
