### ISSUE TITLE
DNS server needs to support multiple IP addresses

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#76]
In both the "add a network" and "add a device" forms, the DNS server field needs to support multiple IP addresses.

**Comment by rudietuesdays** [comment]
@critzo is there a limited number of IPs that would need to be added to the DNS, or should it be unlimited?

Also, verifying that these are the fields that need the ability for multiple IPs:
<img width="932" alt="Screen Shot 2020-09-18 at 11 53 13 AM" src="https://user-images.githubusercontent.com/10843135/93619208-3ce8d280-f9a6-11ea-95fc-db7b1af71973.png">
<img width="560" alt="Screen Shot 2020-09-18 at 11 53 24 AM" src="https://user-images.githubusercontent.com/10843135/93619209-3d816900-f9a6-11ea-9c00-167aaaf6e0a7.png">

**Comment by critzo** [comment]
Hi @rudietuesdays. In the first field that is circled, there should be no limit to the number of IP addresses. It could be one field with comma or space separated IPs. This section is for "network settings", and I think there's another issue to  allow multiple networks to be defined. 

The second field you've circled is for the individual device's static IP (if it is not DHCP assigned). This field will contain one IP address. The field will be left blank if the IP is assigned by DHCP for that device. The field above it that is not circled but is labelled "DNS server" could be auto-populated with the values from the network this device is in, if we add a select item under New Device that first selects a network that had previously been added.

**Comment by jheretic** [comment]
@critzo  quick dumb question, all of these address values are for the networks that are internal to the library, not external, right?

**Comment by critzo** [comment]
@jheretic not a dumb question. Static IPs for devices will all be internal IPs. DNS servers could be either internal IPs or external. For example, some libraries use OpenDNS, others use locally provisioned DNS servers, and some use both.
