### ISSUE TITLE
Dynamic/Static IP address options in Add Device form

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#78]
In the mockups we had the following for static/dynamic IP address on the add device form:
![image](https://user-images.githubusercontent.com/4633345/84507679-33f1b200-ac8f-11ea-9a33-91212ec40f06.png)

However, it makes sense to keep the field as is, but add text that helps the user understand that they don't have to add anything if the device has a DHCP address. Perhaps the "if applicable" text added to the pre-populated field contents: "Static IP (if applicable)"

**Comment by rudietuesdays** [comment]
Self assigning to knock this out!
