### ISSUE TITLE
API should include all fields from all supported tests

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#89]
Testing the import of test results through the Murakami HTTP exporter and Murakami Viz POST API, I've successfully set up one device that uses the HTTP exporter, posting results to the API. However, not all fields for supported tests are included. Fields are aligned with ndt5 and ndt7 tests, but other fields from speedtest-cli are not included. 

The table below is from the output of downloaded the results from Murakami Viz, transposed in columns for readability:

id | 2 | 2 | 2 | 2
-- | -- | -- | -- | --
Test Name | speedtest-cli-single-stream | speedtest-cli-multi-stream | ndt5 | ndt7
Test Error |   |   |   |  
Server Name | Elkridge, MD | Baltimore, MD | ndt-iupui-mlab2-iad04.mlab-oti.measurement-lab.org | ndt-iupui-mlab1-iad03.mlab-oti.measurement-lab.org
Server IP |   |   | 173.205.4.24 | 66.198.10.139
Client IP | 104.145.222.186 | 104.145.222.186 | 104.145.222.186 | 104.145.222.186
Murakami Location | mlab-testbed | mlab-testbed | mlab-testbed | mlab-testbed
Murakami Network Type | home | home | home | home
Murakami Connetion Type | wired | wired | wired | wired
Download UUID |   |   | ndt-b8vgz_1596751018_00000000003146FA | ndt-v69tj_1596672525_000000000033952C
Test Start Time | 2020-09-28T18:05:07.437Z | 2020-09-28T18:04:43.682Z | 2020-09-28T18:03:52.964Z | 2020-09-28T18:04:17.900Z
Test End Time | 2020-09-28T18:05:30.024Z | 2020-09-28T18:05:06.433Z | 2020-09-28T18:04:16.564Z | 2020-09-28T18:04:42.759Z
Download Value | 4739885.74900167 | 6869351.177012082 | 4.461918053406164 | 7.805633884777312
Download Unit | Bit/s | Bit/s | Mbit/s | Mbit/s
Download Error |   |   |   |  
Download Retrans Value |   |   | 0.6033882571362265 | 12.946360622127697
Download Retrans Unit |   |   | % | %
Upload Value | 3700078.6276100725 | 3814007.822823624 | 3.424 | 4.333440063478125
Upload Unit | Bit/s | Bit/s | Mbit/s | Mbit/s
Min RTT Value |   |   | 12.542 | 43.098
Min RTT Unit |   |   | ms | ms

Murakami's output specification for speedtest-cli [single](https://github.com/m-lab/murakami/issues/42) and [multi](https://github.com/m-lab/murakami/issues/43) stream tests includes several fields that are not currently being stored by the API. 

As a guide for which fields are missing, below is a table showing the fields currently in the output of Murakami Viz, the fields present in the speedtest-cli tests, and sample values from a recent speedtest-cli test that was sent to Murakami Viz:

Fields in Murakami Viz export | Fields in speedtest-cli | Sample values, speedtest-cli
-- | -- | --
id |   |  
Test Name | TestName | speedtest-cli-single-stream
Test Error |   |  
Server Name |   |  
  | ServerURL | http://ookla1.ekrgmd.sprintadp.net:8080/speedtest/upload.php
Server IP |   |  
Client IP | ClientIP | 104.145.222.186
Murakami Location | MurakamiLocation | mlab-testbed
Murakami Network Type | MurakamiConnectionType | wired
Murakami Connetion Type | MurakamiNetworkType | home
  | MurakamiDeviceID | d336bd0679b899b17b346861c43a0f75ecc653ce00f2dfdf59dacdfc26c758
Download UUID |   |  
Test Start Time | TestStartTime | 2020-09-28T18:05:07.437125
Test End Time | TestEndTime | 2020-09-28T18:05:30.024170
Download Value | DownloadValue | 4739885.74900167
Download Unit | DownloadUnit | Bit/s
Download Error |   |  
Download Retrans Value |   |  
Download Retrans Unit |   |  
Upload Value | UploadValue | 3700078.62761007
Upload Unit | UploadUnit | Bit/s
Min RTT Value |   |  
Min RTT Unit |   |  
  | Ping | 48.239
  | PingUnit | ms
  | BytesSent | 4653056
  | BytesReceived | 5977032
  | Share | null
  | Timestamp | 2020-09-28T18:05:07.843445Z
  | ServerLat | 39.1978
  | ServerLon | -76.7625
  | ServerName | Elkridge, MD
  | ServerCountry | United States
  | ServerCountryCode | US
  | ServerSponsor | Sprint
  | ServerID | 13658
  | ServerHost | ookla1.ekrgmd.sprintadp.net:8080
  | ServerDistance | 20.3051011479811
  | ServerLatency | 48.239
  | ServerLatencyUnit | ms
  | ClientLat | 39.2891
  | ClientLon | -76.5583
  | Isp | Port Networks
  | IspRating | 3.7
  | Rating | 0
  | IspDownloadAvg | 0
  | IspUploadAvg | 0
  | LoggedIn | 0
  | Country | US

**Comment by jheretic** [comment]
Just adding a note that all this data is collected, the list of fields included in the CSV export just needs to be updated.
